### ISSUE TITLE
Trouble adding emojis

### ISSUE THREAD

**Issue by bchivers-stanford** [giorgimode/SpotMyStatus#34]
I'm struggling to add custom emoji's from the "SpotMyStatus" page within the Slack desktop app.  

For example, my workspace has a :partyblob: emoji.  I type ":partyblob:" or "partyblob", and press enter, and nothing happens.  I've tried default emojis too, like guitar (as suggested in the alt text).

**Comment by giorgimode** [comment]
can you try again and please give me the timestamp of the action? I cannot find anything in the logs. If possible, you can also try the same within the browser and check the network calls for any errors. That'd be helpful for debugging

**Comment by bchivers-stanford** [comment]
I tried via the Slack desktop app at 9:15am PT.  Attached is a screen capture of what I'm seeing.

Note that I am pressing ENTER in this screen capture - nothing happens when I press ENTER
![2021-06-24_09-15-44](https://user-images.githubusercontent.com/59845486/123298127-0c9e0980-d4cd-11eb-91c7-1e132e41b9da.gif)

I'll try the browser version shortly.

**Comment by bchivers-stanford** [comment]
The behavior is the same from the browser in Firefox - I tried at 9:20am PT.

Thanks for your help!

**Comment by giorgimode** [comment]
Unfortunately I don't see the activity in the logs, meaning the command doesn't reach the application at all. It would be quite helpful if you could check your browser's [network activity](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) and see if there are any errors, anything blocked

**Comment by bchivers-stanford** [comment]
I think I've uncovered the issue.  I use Command+ENTER to send messages.  When this preference was set, I couldn't add an emoji, using ENTER or Command+ENTER.  But - as soon as I changed my preferences to use ENTER to send messages, it worked as expected.

**Comment by giorgimode** [comment]
Terrific, good to hear. I am closing the issue if there's nothing else.
