### ISSUE TITLE
Server 502 Error https://spotmystatus.giomo.de/

### ISSUE THREAD

**Issue by chava100f** [giorgimode/SpotMyStatus#40]
Hello I'm using your app that's listed in slack but suddenly doesn't work anymore, I think maybe the server has some errors. https://spotmystatus.giomo.de/ I know this is not a bug on the code but I didn't knew other way to report this error hehe. 

Thank you very much, happy coding.

![badGateWAy](https://user-images.githubusercontent.com/13232234/152625496-5fb38f8e-e1d4-454b-a05b-f32234cae47c.PNG)

**Comment by pythonreactor** [comment]
Had the same issue - can now access the site but still receiving, "This is still a work in progress" message in Slack
![Screen Shot 2022-02-07 at 11 37 56](https://user-images.githubusercontent.com/19892394/152859413-7ffba5f2-cd6d-4273-8050-c025c90533ef.png)

**Comment by chava100f** [comment]
It is Working again! thank you very much!

![imagen](https://user-images.githubusercontent.com/13232234/153034175-da0c09ce-4c59-41a0-90f4-a353bdffd5e5.png)

**Comment by giorgimode** [comment]
Sometimes AWS shuffles the instances, especially on the weekend, that messes up my nginx setup. Sorry for the trouble
