### ISSUE TITLE
Make the SpotStatus clickable so that people can click and listen to the song if they like?

### ISSUE THREAD

**Issue by navidcy** [giorgimode/SpotMyStatus#41]
Will that be possible?

cc: @glwagner

**Comment by giorgimode** [comment]
Hey @navidcy, that is an awesome idea I'd been dying to implement for a long time. However, I am confined to the capabilities provided by Slack and at the moment user's status is not interactive. In the words of Howard Stark, I am limited by the technology of my time. If Slack API somehow enables this, I'd be bringing the feature in no time

**Comment by navidcy** [comment]
Thanks. Feel free to close if you like.

**Comment by glwagner** [comment]
May our shackles be unbound some-day.

**Comment by glwagner** [comment]
Maybe it's possible to issue a command like `/play` in a chat that prints a link ?

**Comment by giorgimode** [comment]
hey @glwagner, do you mean printing the link to your currently playing song? That should be relatively easy to add I think

**Comment by glwagner** [comment]
Yeah! Or perhaps we can issue a command to get the songs that other people in a direct chat are listening to ? Either would be neat !

**Comment by giorgimode** [comment]
So, an update on the feature:
When you click a button(send a command) from the chat, Slack doesn't provide the list of participants, only id of the conversation. One could query the Slack API for the members of the conversation but that requires additional privileges, which I'd like to avoid. I implemented a workaround. You can issue a command `/spotme links` or just hit the button at the top named `Your team's current tracks` to print the list of all the tracks that your teammates are listening to. 
Keep in mind that teammate's current track is only shown if it's currently set on their status to respect their privacy.

**Comment by glwagner** [comment]
That's pretty sweet! I need more of @navidcy's tracks in my life.
