### ISSUE TITLE
Am I missing something...?

### ISSUE THREAD

**Issue by chaoscreater** [giorgimode/SpotMyStatus#48]
Not sure what I'm missing, but it's not syncing whatever I'm playing in Spotify to my Slack. 

Pretty sure I've configured it correctly, because I can see my Spotify devices and I can see the custom Slack emojis, so it's definitely linked to the correct accounts.

I've tried using `/SpotMe play` as well and it says Status updates have been resumed, but still no status sync. Closed and restarted Spotify on Windows, same thing. Slack and Spotify fully up to date.

I even deleted it and re-added it and it's the same thing, no sync. Apps like GetPulse updates my Slack status just fine.

![image](https://user-images.githubusercontent.com/18227319/192649262-d599afa6-cbd9-463e-a02c-471a3d114c7f.png)

**Comment by giorgimode** [comment]
12PM is noon, you're outside syncing hours.

I responded to your [ticket ](https://giorgimode.myjetbrains.com/youtrack/issue/SMS-86/Am-I-missing-something)earlier today;
