### ISSUE TITLE
Slack invocation fails with SSL error.

### ISSUE THREAD

**Issue by VPanjeta** [giorgimode/SpotMyStatus#50]
Hi.  

I Added the latest version of the bot from Slack Bot section. 
When I try to invoke bot by `/spotme` . I get an error saying `/spotme failed with the error “ssl_cacert”`
![image](https://user-images.githubusercontent.com/16860039/201719967-d54841c6-5f3b-4303-a823-f106aba3d2dc.png)

Thanks

**Comment by giorgimode** [comment]
Many thanks for bringing this to my attention. I rolled over the certificates over the weekend and missed to include intermediary ca in the bundle. Issue is now fixed
